from synapse_realworld.cli import app
from synapse_realworld.cli_assignments import register_assignment_commands
from synapse_realworld.cli_experiments import register_experiment_commands
from synapse_realworld.cli_market import register_market_commands
from synapse_realworld.cli_modelops import register_modelops_commands
from synapse_realworld.cli_production import register_production_commands

register_market_commands(app)
register_experiment_commands(app)
register_assignment_commands(app)
register_modelops_commands(app)
register_production_commands(app)

__all__ = ["app"]
