from __future__ import annotations

from synapse_realworld.connectors.csv import CsvEventProfile


LAA_CONNECTOR_PROFILES: dict[str, CsvEventProfile] = {
    "crm_leads": CsvEventProfile(
        name="laa-crm-leads-v1",
        event_type="lead_created",
        entity_type="party",
        entity_id_column="contact_id",
        occurred_at_column="created_at",
        source_event_key_column="lead_id",
        payload_columns=(
            "lead_source",
            "campaign_id",
            "content_id",
            "sales_owner_id",
            "decision_stage",
        ),
        required_columns=("lead_source",),
        pseudonymize_entity_id=True,
    ),
    "crm_qualification": CsvEventProfile(
        name="laa-crm-qualification-v1",
        event_type="qualification_observed",
        entity_type="household",
        entity_id_column="household_id",
        occurred_at_column="captured_at",
        source_event_key_column="qualification_id",
        payload_columns=(
            "purchase_purpose",
            "household_size_band",
            "children_band",
            "household_income_band",
            "liquid_capital_band",
            "max_monthly_payment_band",
            "purchase_horizon",
            "workplace_zone",
            "stated_max_travel_min",
            "preferred_product_type",
            "shortlisted_unit_code",
            "competitor_mentioned",
            "outside_option",
        ),
        pseudonymize_entity_id=True,
    ),
    "sap_outcomes": CsvEventProfile(
        name="laa-sap-outcomes-v1",
        event_type="decision_outcome_verified",
        entity_type="household",
        entity_id_column="household_id",
        occurred_at_column="occurred_at",
        source_event_key_column="outcome_id",
        payload_columns=(
            "outcome_type",
            "unit_code",
            "offer_id",
            "booking_amount",
            "cancellation_reason",
            "verified",
        ),
        required_columns=("outcome_type",),
        pseudonymize_entity_id=True,
    ),
    "inventory": CsvEventProfile(
        name="laa-inventory-v1",
        event_type="unit_inventory_observed",
        entity_type="unit",
        entity_id_column="unit_code",
        occurred_at_column="snapshot_at",
        source_event_key_column="snapshot_row_id",
        payload_columns=(
            "product_type",
            "inventory_state",
            "lot_area_m2",
            "built_area_m2",
            "corner_flag",
            "orientation",
        ),
        required_columns=("inventory_state",),
    ),
    "offers": CsvEventProfile(
        name="laa-offers-v1",
        event_type="offer_observed",
        entity_type="unit",
        entity_id_column="unit_code",
        occurred_at_column="effective_from",
        source_event_key_column="offer_id",
        payload_columns=(
            "list_price_vnd",
            "net_price_vnd",
            "discount_pct",
            "incentive_cash_vnd",
            "payment_plan_code",
            "down_payment_pct",
            "monthly_payment_est",
            "effective_to",
        ),
        required_columns=("list_price_vnd",),
    ),
    "ads": CsvEventProfile(
        name="laa-ads-v1",
        event_type="campaign_performance_observed",
        entity_type="campaign",
        entity_id_column="campaign_id",
        occurred_at_column="date",
        source_event_key_column="row_id",
        payload_columns=(
            "platform",
            "adset_id",
            "creative_id",
            "creative_version",
            "message_angle",
            "target_segment",
            "spend_vnd",
            "impressions",
            "clicks",
            "leads",
            "qualified_leads",
            "appointments",
            "site_tours",
            "bookings",
            "contracts",
        ),
        required_columns=("platform",),
    ),
    "website": CsvEventProfile(
        name="laa-website-events-v1",
        event_type="web_engagement_observed",
        entity_type="party",
        entity_id_column="visitor_id",
        occurred_at_column="occurred_at",
        source_event_key_column="event_id",
        payload_columns=(
            "event_name",
            "utm_source",
            "utm_campaign",
            "content_id",
            "unit_code",
            "session_id",
        ),
        required_columns=("event_name",),
        pseudonymize_entity_id=True,
    ),
}


def get_laa_profile(name: str) -> CsvEventProfile:
    try:
        return LAA_CONNECTOR_PROFILES[name]
    except KeyError as exc:
        available = ", ".join(sorted(LAA_CONNECTOR_PROFILES))
        raise ValueError(f"unknown LAA connector profile: {name}; available: {available}") from exc
